### ISSUE TITLE
why are there two bulk fast5 files for direct Notts RNA run2 ?

### ISSUE THREAD

**Issue by Huanle** [nanopore-wgs-consortium/NA12878#99]
Hi There,

Thanks a lot for sharing the data!
Why are there [rs1 bulkfast5](https://s3.amazonaws.com/nanopore-human-wgs/rna/bulkFiles/PLSP61583_20171027_FAH20402_MN18658_sequencing_run_Notts_Run2_20171027_DirectRNA_rs1_27930.fast5) and [bulk fast5](https://s3.amazonaws.com/nanopore-human-wgs/rna/bulkFiles/PLSP61583_20171027_FAH20402_MN18658_sequencing_run_Notts_Run2_20171027_DirectRNA_36840.fast5) for the same run, i.e., Notts direct RNA run2?

**Comment by mattloose** [comment]
Because our practice at that point for run naming was to add "rs" for restart and then a number for the number of times a run had been restarted. So these bulk fast 5 files were generated from exactly the same library and flowcell etc. The only difference is that the run was stopped and restarted. Hope that makes sense.
